### ISSUE TITLE
Consider returning `feathers.SKIP` whenever context.result is set.

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/feathers-hooks-common#355]
This would skip all following hooks.

**Comment by beeplin** [comment]
you mean in before hooks?

I think there are always cases that people set `context.result` in order to skip the actual service method calling, but don't want to skip all following hooks. If they do want to skip following hooks they could always write a hook to check `context.result` and return `feathers.SKIP`.

In fact we can provide such a hook: 

```js
const skipFollowingHooksWhenResultIsSet = () => context => context.result ? feathers.SKIP : context
```

**Comment by eddyystop** [comment]
Added `skipRemainingHooks(predicate = context => !!context.result)` in v4.8.0.

Docs updated.
